/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ConfigPreset } from "../types";

export const claudePresets: ConfigPreset[] = [
  // === 官方 ===
  {
    id: "claude-official",
    toolId: "claude",
    name: "Claude Official",
    websiteUrl: "https://www.anthropic.com/claude-code",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  // === 国产官方 ===
  {
    id: "claude-deepseek",
    toolId: "claude",
    name: "DeepSeek",
    websiteUrl: "https://platform.deepseek.com",
    category: "cn_official",
    badge: "国产",
    featured: true,
    baseUrl: "https://api.deepseek.com/anthropic",
    model: "DeepSeek-V3.2",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-zhipu",
    toolId: "claude",
    name: "Zhipu GLM",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    model: "glm-5",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-zhipu-en",
    toolId: "claude",
    name: "Zhipu GLM en",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.z.ai/api/anthropic",
    model: "glm-5",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-bailian",
    toolId: "claude",
    name: "Bailian",
    websiteUrl: "https://bailian.console.aliyun.com",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-bailian-coding",
    toolId: "claude",
    name: "Bailian For Coding",
    websiteUrl: "https://bailian.console.aliyun.com",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-kimi",
    toolId: "claude",
    name: "Kimi",
    websiteUrl: "https://platform.moonshot.cn/console",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.moonshot.cn/anthropic",
    model: "kimi-k2.5",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-kimi-coding",
    toolId: "claude",
    name: "Kimi For Coding",
    websiteUrl: "https://www.kimi.com/coding/docs/",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.kimi.com/coding/",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-stepfun",
    toolId: "claude",
    name: "StepFun",
    websiteUrl: "https://platform.stepfun.ai",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.stepfun.ai/v1",
    model: "step-3.5-flash",
    authField: "ANTHROPIC_AUTH_TOKEN",
    apiFormat: "openai_chat",
    endpointCandidates: ["https://api.stepfun.ai/v1"],
  },
  {
    id: "claude-modelscope",
    toolId: "claude",
    name: "ModelScope",
    websiteUrl: "https://modelscope.cn",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api-inference.modelscope.cn",
    model: "ZhipuAI/GLM-5",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-minimax",
    toolId: "claude",
    name: "MiniMax",
    websiteUrl: "https://platform.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.minimaxi.com/anthropic",
    model: "MiniMax-M2.7",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-minimax-en",
    toolId: "claude",
    name: "MiniMax en",
    websiteUrl: "https://platform.minimax.io",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.minimax.io/anthropic",
    model: "MiniMax-M2.7",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-doubaoseed",
    toolId: "claude",
    name: "DouBaoSeed",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    apiKeyUrl: "https://www.volcengine.com/product/doubao",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    model: "doubao-seed-2-0-code-preview-latest",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-bailing",
    toolId: "claude",
    name: "BaiLing",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.tbox.cn/api/anthropic",
    model: "Ling-2.5-1T",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-longcat",
    toolId: "claude",
    name: "Longcat",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.longcat.chat/anthropic",
    model: "LongCat-Flash-Chat",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-xiaomi-mimo",
    toolId: "claude",
    name: "Xiaomi MiMo",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    model: "mimo-v2-pro",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  // === 聚合 ===
  {
    id: "claude-aihubmix",
    toolId: "claude",
    name: "AiHubMix",
    websiteUrl: "https://aihubmix.com",
    apiKeyUrl: "https://aihubmix.com",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://aihubmix.com",
    model: "",
    authField: "ANTHROPIC_API_KEY",
    endpointCandidates: ["https://aihubmix.com", "https://api.aihubmix.com"],
  },
  {
    id: "claude-siliconflow",
    toolId: "claude",
    name: "SiliconFlow",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api.siliconflow.cn",
    model: "Pro/MiniMaxAI/MiniMax-M2.7",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-siliconflow-en",
    toolId: "claude",
    name: "SiliconFlow en",
    websiteUrl: "https://siliconflow.com",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api.siliconflow.com",
    model: "MiniMaxAI/MiniMax-M2.7",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-dmxapi",
    toolId: "claude",
    name: "DMXAPI",
    websiteUrl: "https://www.dmxapi.cn",
    apiKeyUrl: "https://www.dmxapi.cn",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://www.dmxapi.cn",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
    endpointCandidates: ["https://www.dmxapi.cn", "https://api.dmxapi.cn"],
  },
  {
    id: "claude-openrouter",
    toolId: "claude",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://openrouter.ai/api",
    model: "anthropic/claude-sonnet-4.6",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
  {
    id: "claude-novita",
    toolId: "claude",
    name: "Novita AI",
    websiteUrl: "https://novita.ai",
    apiKeyUrl: "https://novita.ai",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api.novita.ai/anthropic",
    model: "zai-org/glm-5",
    authField: "ANTHROPIC_AUTH_TOKEN",
    apiFormat: "openai_chat",
    endpointCandidates: ["https://api.novita.ai/anthropic"],
  },
  {
    id: "claude-nvidia",
    toolId: "claude",
    name: "Nvidia",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://integrate.api.nvidia.com",
    model: "moonshotai/kimi-k2.5",
    authField: "ANTHROPIC_AUTH_TOKEN",
    apiFormat: "openai_chat",
  },
  {
    id: "claude-compshare",
    toolId: "claude",
    name: "Compshare",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api.modelverse.cn",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
    endpointCandidates: ["https://api.modelverse.cn"],
  },
  // === 云厂商 ===
  {
    id: "claude-github-copilot",
    toolId: "claude",
    name: "GitHub Copilot",
    websiteUrl: "https://github.com/features/copilot",
    category: "third_party",
    badge: "Copilot",
    baseUrl: "https://api.githubcopilot.com",
    model: "claude-opus-4.6",
    authField: "ANTHROPIC_AUTH_TOKEN",
    apiFormat: "openai_chat",
    providerType: "github_copilot",
    requiresOAuth: true,
  },
  {
    id: "claude-aws-bedrock",
    toolId: "claude",
    name: "AWS Bedrock (AKSK)",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud_provider",
    badge: "AWS",
    baseUrl: "https://bedrock-runtime.${AWS_REGION}.amazonaws.com",
    model: "global.anthropic.claude-opus-4-6-v1",
    authField: "ANTHROPIC_AUTH_TOKEN",
    templateValues: {
      AWS_REGION: { label: "AWS Region", placeholder: "us-west-2" },
      AWS_ACCESS_KEY_ID: { label: "Access Key ID", placeholder: "AKIA..." },
      AWS_SECRET_ACCESS_KEY: { label: "Secret Access Key", placeholder: "your-secret-key" },
    },
  },
  // === 自定义 ===
  {
    id: "claude-custom",
    toolId: "claude",
    name: "自定义",
    category: "custom",
    baseUrl: "",
    model: "",
    authField: "ANTHROPIC_AUTH_TOKEN",
  },
];
