/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ConfigPreset } from "../types";

export const codexPresets: ConfigPreset[] = [
  // === 官方 ===
  {
    id: "codex-official",
    toolId: "codex",
    name: "OpenAI Official",
    websiteUrl: "https://chatgpt.com/codex",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "",
    model: "",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
  },
  {
    id: "codex-azure",
    toolId: "codex",
    name: "Azure OpenAI",
    websiteUrl: "https://learn.microsoft.com/azure/ai-foundry/openai/how-to/codex",
    category: "third_party",
    badge: "Azure",
    featured: true,
    baseUrl: "https://YOUR_RESOURCE_NAME.openai.azure.com/openai",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
    endpointCandidates: ["https://YOUR_RESOURCE_NAME.openai.azure.com/openai"],
  },
  // === 聚合 ===
  {
    id: "codex-aihubmix",
    toolId: "codex",
    name: "AiHubMix",
    websiteUrl: "https://aihubmix.com",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://aihubmix.com/v1",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
    endpointCandidates: ["https://aihubmix.com/v1", "https://api.aihubmix.com/v1"],
  },
  {
    id: "codex-dmxapi",
    toolId: "codex",
    name: "DMXAPI",
    websiteUrl: "https://www.dmxapi.cn",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://www.dmxapi.cn/v1",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
    endpointCandidates: ["https://www.dmxapi.cn/v1"],
  },
  {
    id: "codex-compshare",
    toolId: "codex",
    name: "Compshare",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://api.modelverse.cn/v1",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
    endpointCandidates: ["https://api.modelverse.cn/v1"],
  },
  {
    id: "codex-openrouter",
    toolId: "codex",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
  },
  // === 自定义 ===
  {
    id: "codex-custom",
    toolId: "codex",
    name: "自定义",
    category: "custom",
    baseUrl: "",
    model: "gpt-5.4",
    codexWireApi: "responses",
    codexReasoningEffort: "high",
  },
];
