/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ConfigPreset } from "../types";

export const hermesPresets: ConfigPreset[] = [
  {
    id: "hermes-nous",
    toolId: "hermes",
    name: "Nous Portal",
    websiteUrl: "https://portal.nousresearch.com",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "https://portal.nousresearch.com/v1",
    model: "anthropic/claude-sonnet-4.6",
    hermesProvider: "nous",
    hermesApiKeyEnv: "",
  },
  {
    id: "hermes-openrouter",
    toolId: "hermes",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4.6",
    hermesProvider: "openrouter",
    hermesApiKeyEnv: "OPENROUTER_API_KEY",
  },
  {
    id: "hermes-anthropic-openrouter",
    toolId: "hermes",
    name: "Anthropic via OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "Anthropic",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4.6",
    hermesProvider: "openrouter",
    hermesApiKeyEnv: "OPENROUTER_API_KEY",
  },
  {
    id: "hermes-gemini",
    toolId: "hermes",
    name: "Gemini",
    websiteUrl: "https://ai.google.dev/",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    category: "official",
    badge: "官方",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    model: "gemini-2.5-pro",
    hermesProvider: "gemini",
    hermesApiKeyEnv: "GEMINI_API_KEY",
  },
  {
    id: "hermes-zai",
    toolId: "hermes",
    name: "Z.AI / GLM",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.z.ai/v1",
    model: "glm-5",
    hermesProvider: "zai",
    hermesApiKeyEnv: "GLM_API_KEY",
  },
  {
    id: "hermes-kimi",
    toolId: "hermes",
    name: "Kimi",
    websiteUrl: "https://platform.moonshot.ai",
    apiKeyUrl: "https://platform.moonshot.ai/console/api-keys",
    category: "cn_official",
    badge: "国产",
    baseUrl: "https://api.moonshot.ai/v1",
    model: "kimi-k2.5",
    hermesProvider: "kimi-coding",
    hermesApiKeyEnv: "KIMI_API_KEY",
  },
  {
    id: "hermes-custom",
    toolId: "hermes",
    name: "自定义",
    category: "custom",
    baseUrl: "",
    model: "",
    hermesProvider: "custom",
    hermesApiKeyEnv: "OPENROUTER_API_KEY",
  },
];
