/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ConfigPreset } from "../types";

export const opencodePresets: ConfigPreset[] = [
  {
    id: "opencode-openai",
    toolId: "opencode",
    name: "OpenAI Responses",
    websiteUrl: "https://platform.openai.com/",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-5.4",
    npm: "@ai-sdk/openai",
    openCodeContextLimit: "400000",
    openCodeOutputLimit: "128000",
    openCodeInputModalities: "text,image",
    openCodeOutputModalities: "text",
    openCodeVariantName: "high",
    openCodeReasoningEffort: "high",
  },
  {
    id: "opencode-gemini",
    toolId: "opencode",
    name: "Google (Gemini)",
    websiteUrl: "https://ai.google.dev/",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    model: "gemini-3-flash-preview",
    npm: "@ai-sdk/google",
    openCodeContextLimit: "1048576",
    openCodeOutputLimit: "65536",
    openCodeInputModalities: "text,image,pdf,video,audio",
    openCodeOutputModalities: "text",
    openCodeVariantName: "high",
    openCodeIncludeThoughts: true,
    openCodeThinkingLevel: "high",
  },
  {
    id: "opencode-anthropic",
    toolId: "opencode",
    name: "Anthropic",
    websiteUrl: "https://www.anthropic.com/api",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    category: "official",
    badge: "官方",
    featured: true,
    baseUrl: "https://api.anthropic.com",
    model: "claude-opus-4-6",
    npm: "@ai-sdk/anthropic",
    openCodeContextLimit: "1000000",
    openCodeOutputLimit: "128000",
    openCodeInputModalities: "text,image,pdf",
    openCodeOutputModalities: "text",
    openCodeVariantName: "max",
    openCodeEffort: "max",
  },
  {
    id: "opencode-openrouter",
    toolId: "opencode",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4",
    npm: "@ai-sdk/openai-compatible",
    openCodeContextLimit: "200000",
    openCodeOutputLimit: "64000",
    openCodeInputModalities: "text,image",
    openCodeOutputModalities: "text",
    endpointCandidates: ["https://openrouter.ai/api/v1"],
  },
  {
    id: "opencode-custom",
    toolId: "opencode",
    name: "自定义",
    category: "custom",
    baseUrl: "",
    model: "",
    npm: "@ai-sdk/openai-compatible",
  },
];
