/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ConfigPreset } from "../types";

export const openclawPresets: ConfigPreset[] = [
  {
    id: "openclaw-deepseek",
    toolId: "openclaw",
    name: "DeepSeek",
    websiteUrl: "https://platform.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    category: "cn_official",
    badge: "国产",
    featured: true,
    baseUrl: "https://api.deepseek.com/v1",
    model: "deepseek-chat",
    apiProtocol: "openai-completions",
    openClawContextWindow: "64000",
    openClawCostInput: "0.0005",
    openClawCostOutput: "0.002",
    suggestedPrimaryModel: "deepseek/deepseek-chat",
    suggestedFallbackModels: "deepseek/deepseek-reasoner",
    modelCatalogAlias: "DeepSeek",
  },
  {
    id: "openclaw-bedrock",
    toolId: "openclaw",
    name: "AWS Bedrock",
    websiteUrl: "https://aws.amazon.com/bedrock/",
    category: "cloud_provider",
    badge: "AWS",
    featured: true,
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    model: "global.anthropic.claude-sonnet-4-6",
    apiProtocol: "bedrock-converse-stream",
    openClawContextWindow: "1000000",
    suggestedPrimaryModel: "anthropic/claude-sonnet-4-6",
    modelCatalogAlias: "Claude Sonnet 4.6",
  },
  {
    id: "openclaw-openrouter",
    toolId: "openclaw",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    category: "aggregator",
    badge: "聚合",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "anthropic/claude-sonnet-4",
    apiProtocol: "openai-responses",
    modelCatalogAlias: "Claude Sonnet",
    endpointCandidates: ["https://openrouter.ai/api/v1"],
  },
  {
    id: "openclaw-custom",
    toolId: "openclaw",
    name: "自定义",
    category: "custom",
    baseUrl: "",
    model: "",
    apiProtocol: "openai-completions",
  },
];
