// Settings 页面中两个大型 useMemo 标签字典工厂，原本占用 ~110 行内联代码。
import type { I18n, Locale } from "../../lib/i18n";

function localize(loc: Locale, zh: string, en: string, ja?: string) {
  return loc === "zh" ? zh : loc === "ja" ? (ja ?? en) : en;
}

export function buildMigrationCenterLabels(i: I18n, loc: Locale) {
  return {
    title: i.settings.migrationCenter,
    description: i.settings.migrationCenterDesc,
    readyLabel: i.settings.migrationCenterReady,
    activeLabel: loc === "zh" ? "当前展开" : "Open",
    viewLabel: loc === "zh" ? "查看" : "View",
    importSummary: i.settings.importSummary,
    importSummaryPending: i.settings.importSummaryPending,
    pendingImports: i.settings.pendingImports,
    pendingImportsDesc: i.settings.pendingImportsDesc,
    migrationHealth: i.settings.migrationHealth,
    authGuide: i.settings.authGuide,
    migrationExport: i.settings.migrationExport,
    migrationExporting: i.settings.migrationExporting,
    migrationImport: i.settings.migrationImport,
    migrationImporting: i.settings.migrationImporting,
    pendingImportsRepairAll: i.settings.pendingImportsRepairAll,
    pendingImportsRepairingAll: i.settings.pendingImportsRepairingAll,
    fullRescan: i.settings.fullRescan,
    fullRescanning: i.settings.fullRescanning,
    importSummaryEmpty: i.settings.importSummaryEmpty,
    importSummaryBackup: i.settings.importSummaryBackup,
    openPathLabel: i.settings.authGuideOpenPath,
    migrationCenterLastRescanEmpty: i.settings.migrationCenterLastRescanEmpty,
    importSummaryImportedAt: i.settings.importSummaryImportedAt,
    importSummaryData: i.settings.importSummaryData,
    importSummaryToolConfigs: i.settings.importSummaryToolConfigs,
    importSummarySkills: i.settings.importSummarySkills,
    importSummaryFiles: i.settings.importSummaryFiles,
    pendingImportsEmpty: i.settings.pendingImportsEmpty,
    pendingImportsOldPath: i.settings.pendingImportsOldPath,
    pendingImportsNewPath: i.settings.pendingImportsNewPath,
    pendingImportsPick: i.settings.pendingImportsPick,
    pendingImportsApply: i.settings.pendingImportsApply,
    pendingImportsApplying: i.settings.pendingImportsApplying,
    pendingImportsFiles: i.settings.pendingImportsFiles,
    pendingImportsAutoMatch: i.settings.pendingImportsAutoMatch,
    pendingImportsAutoMatching: i.settings.pendingImportsAutoMatching,
    pendingImportsAutoMatchDesc: i.settings.pendingImportsAutoMatchDesc,
    migrationHealthDesc: i.settings.migrationHealthDesc,
    migrationHealthRefresh: i.settings.migrationHealthRefresh,
    migrationHealthRefreshing: i.settings.migrationHealthRefreshing,
    migrationHealthReady: i.settings.migrationHealthReady,
    migrationHealthCliMissing: i.settings.migrationHealthCliMissing,
    migrationHealthCli: i.settings.migrationHealthCli,
    migrationHealthConfigDir: i.settings.migrationHealthConfigDir,
    migrationHealthConfigDirMissing: i.settings.migrationHealthConfigDirMissing,
    migrationHealthConfigFile: i.settings.migrationHealthConfigFile,
    migrationHealthConfigMissing: i.settings.migrationHealthConfigMissing,
    migrationHealthMcpConfig: i.settings.migrationHealthMcpConfig,
    migrationHealthMcpMissing: i.settings.migrationHealthMcpMissing,
    migrationHealthSkillsDir: i.settings.migrationHealthSkillsDir,
    migrationHealthSkillsMissing: i.settings.migrationHealthSkillsMissing,
    migrationHealthCustomPath: i.settings.migrationHealthCustomPath,
    migrationHealthInstall: i.settings.migrationHealthInstall,
    migrationHealthBootstrap: i.settings.migrationHealthBootstrap,
    migrationHealthBootstrapping: i.settings.migrationHealthBootstrapping,
    migrationHealthPath: i.settings.migrationHealthPath,
    migrationHealthStatusOk: i.settings.migrationHealthStatusOk,
    migrationHealthStatusMissing: i.settings.migrationHealthStatusMissing,
    authGuideDesc: i.settings.authGuideDesc,
    authGuideReady: i.settings.authGuideReady,
    authGuideCodexLogin: i.settings.authGuideCodexLogin,
    authGuideGeminiKey: i.settings.authGuideGeminiKey,
    authGuideCopyCommand: i.settings.authGuideCopyCommand,
    authGuideCopyPath: i.settings.authGuideCopyPath,
    authGuidePrepareFile: i.settings.authGuidePrepareFile,
    authGuideOpenDocs: i.settings.authGuideOpenDocs,
    rescanMcp: i.settings.rescanMcp,
    rescanSkills: i.settings.rescanSkills,
    rescanHooks: i.settings.rescanHooks,
    rescanDocs: i.settings.rescanDocs,
    rescanWorkflows: i.settings.rescanWorkflows,
    rescanConfigRoots: i.settings.rescanConfigRoots,
  };
}

export function buildAppUpdateLabels(i: I18n, loc: Locale) {
  return {
    appUpdate: i.settings.appUpdate,
    currentVersion: i.settings.currentVersion,
    checkForUpdate: i.settings.checkForUpdate,
    checking: i.settings.checking,
    updateAvailable: i.settings.updateAvailable,
    downloading: i.settings.downloading,
    installUpdate: i.settings.installUpdate,
    updateNotConfigured: i.settings.updateNotConfigured,
    noUpdate: i.settings.noUpdate,
    updateFailed: i.settings.updateFailed,
    disabledTitle: localize(
      loc,
      "已被 DISABLE_AUTOUPDATER 环境变量禁用",
      "Disabled by the DISABLE_AUTOUPDATER environment variable",
      "DISABLE_AUTOUPDATER 環境変数により無効化されています",
    ),
    disabledDescription: localize(
      loc,
      "当前会跳过应用更新检查与在线安装。移除该环境变量后重新启动 CCHub，即可恢复正常更新流程。",
      "App update checks and in-app install are skipped while this environment variable is set. Remove it and restart CCHub to restore normal updates.",
      "この環境変数が設定されている間、アプリ更新確認とアプリ内インストールはスキップされます。削除して CCHub を再起動すると通常の更新に戻ります。",
    ),
    disabledCheckDescription: localize(
      loc,
      "更新检查已被环境变量短路",
      "Update checks are short-circuited by environment configuration",
      "環境設定により更新確認は短絡されています",
    ),
    openDownloadsLabel: loc === "zh" ? "前往下载页" : "Open Downloads",
    releaseOnlyDescription:
      loc === "zh"
        ? "已通过发布页检测到新版本。当前构建未提供在线安装清单，将打开下载页手动更新。"
        : "A newer release was found from GitHub. This build does not have an online install manifest, so the download page will be opened.",
  };
}
